config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get '/top' => 'homes#top'

  get '/books'  => 'books#index' ,as:'books'
  post 'books' => 'books#create'

  # get 'books/index'  => 'books#new'
  # get 'books' => 'books#index'

  get 'books/new/:id' => 'books#show'
  get 'books/:id' => 'books#show',as: 'show'


  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
#   delete 'books/new' => 'books#destroy', as: 'destroy_book'

 resources :books
# Railsのルーティングは、「上からの記載順に」マッチ
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



# https://railsguides.jp/routing.html参照
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # 新規作成/一覧画面(画面内)
  def index
  @books = Book.all
  @book = Book.new
  end

  # def index
  #   @books = Book.all
  # end

  # 新規作成（コントローラ内)
  def create

    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "successfully"
      redirect_to show_path(@book.id)

    else
      @books = Book.all
      render :index

    end
  end
  # 詳細画面
  def show
    @book = Book.find(params[:id])
  end

  # 編集(edit&update)
  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to show_path(@book.id)
    else
      render :edit

    end
  end
  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end


   # ストロングパラメータ
   private

   def book_params
     params.require(:book).permit(:title, :body)
   end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
<% @book.errors.full_messages.each do |message| %>
      <div class="Error-message">
        <%= message %>_error
      </div>
    <% end %>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>
<p><span><%= link_to "Show", show_path(@book.id) %></span>|<span><%= link_to "Back", books_path %></span></p>

app/views/books/index.html.erb
<h1>Books</h1>

<div class="index">

<table>
 <thead>
  <tr>
  <th>Title</th>
  <th>Body</th>
  <th colspan="3"></th>
  </tr>
 </thead>

 <tbody>
  <tr>
  <% @books.each do |book| %>
  <td>
  <div class="box-title">
  <span class="list-title">
  <%= book.title %>
  </span>
  </div>
  </td>

  <td>
  <div class="box-body">
  <span class="list-body">
  <%= book.body %>
  </span>
  </div>
  </td>

  <td>
  <div class="box">
  <span><%= link_to "Show", show_path(book.id) %><span>
  <span><%= link_to "Edit", edit_book_path(book.id) %></span>
  <span><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></span>
  </div>
  </td>

</tbody>

<% end %>
</tr>
</table>

<h2>New book</h2>


<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
    <% @book.errors.full_messages.each do |message| %>
      <div class="Error-message">
       <%= message %>_error
      </div>
    <% end %>
<% end %>


<!-- form_with部分 -->
 <%= form_with model: @book do |f| %>

  <h4>Title</h4></h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Create Book' %>

 <% end %>

 <!--投稿に成功しサクセスメッセージが表示されるか (FAIL2-->
 <!--更新に成功しサクセスメッセージが表示されるか (FAILED - 6)-->
 <!--     更新に失敗しエラーメッセージが表示されるか (FAILE-->

app/views/books/new.html.erb
<h1>Books</h1>

<div class="index">

<table>
 <thead>
  <tr>
  <th>Title</th>
  <th>Body</th>
  <th colspan="3"></th>
  </tr>
 </thead>

 <tbody>
  <tr>
  <% @books.each do |book| %>
  <td>
  <div class="box-title">
  <span class="list-title">
  <%= book.title %>
  </span>
  </div>
  </td>

  <td>
  <div class="box-body">
  <span class="list-body">
  <%= book.body %>
  </span>
  </div>
  </td>

  <td>
  <div class="box">
  <span><%= link_to "show", show_path(book.id) %><span>
  <span><%= link_to "edit", edit_book_path(book.id) %></span>
  <span><%= link_to "destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></span>
  </div>
  </td>

</tbody>

<% end %>
</tr>
</table>

<h2>New book</h2>

<% if @book.errors.any? %>
  <ul>
   <%= @book.errors.count %>errors prohibited this book from being saved:
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %>_error</li>
    <% end %>
  </ul>
<% end %>


<!-- form_with部分 -->
 <%= form_with model: @book do |f| %>

  <h4>Title</h4></h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Create Book' %>

 <% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>

<p>Title:<span><%= @book.title %></span></p>
<br>
<p>Body:<span><%= @book.body %></span></p>

<br>
<p>
  <span><%= link_to "Edit", edit_book_path(@book.id) %></span>|<span><%= link_to "Back", books_path %></span>

</p>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>

<div class="top-coment">

<p>Bookers では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<span><%= link_to "start", books_path %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">-->
  </head>

  <body>

    <header>
    </header>

    <nav>
    </nav>

    <main>
    <%= yield %>
    </main>
  </body>
</html>